### ISSUE TITLE
Annotations for the files from Jet Framework 

### ISSUE THREAD

**Issue by doyubkim** [utilForever/CubbyFlow-v0#3]
One of the purposes of restructuring CubbyFlow and branching out to CubbyFlow-v0 is to distinguish CubbyFlow’s own code vs copied code from Jet Framework. Since this v0 repo (or “branch”) is still going to keep the copied code, please add a comment in those files stating the origin (Jet Framework, corresponding file and authors) unless this v0 repo is going to be a private repo.

**Comment by doyubkim** [comment]
Also, before this repo diverge from Jet Framework and gets its own codes, please rephrase the readme file stating that most of the code is copied from Jet Framework and the book. This will hopefully prevent the media issue we had before.

**Comment by utilForever** [comment]
Thank you for your feedback. I will reflect on today.

**Comment by utilForever** [comment]
@doyubkim I updated codes and readme file. Please check it. :^)

**Comment by doyubkim** [comment]
LGTM, thanks for the quick response!
